name: "Test"
on:
  push:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: |
          env GITHUB_TOKEN=${{ env.GITHUB_TOKEN }} GITHUB_REPOSITORY=${{ env.repository }} ./update_release.py
          nix flake check
